menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/yunxu-it
    About: /about
favicon: http://onshks1vz.bkt.clouddn.com/20170901194821_qHtiKc_logo_transparent.png
logo: http://onshks1vz.bkt.clouddn.com/logo_blue_round.png

# Comment
disqus: winxo

# Analytics
# google-analytics:
#ga: UA-65933410-1

# Copyright Infomation
startyear: 2014
