menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/yunxu-it
    About: /about
favicon: /images/icon.png
logo: /images/3.png

# Comment
disqus: winxo

# Analytics
# google-analytics:
#ga: UA-65933410-1

# Copyright Infomation
startyear: 2014
